apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app: payment-service
    environment: prod
    version: 3.3.0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: 3.3.0
    spec:
      containers:
      - name: payment-service
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: VERSION
          value: "3.3.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: payment-service
