apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: components/api-gateway/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
