apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing-service-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: components/billing-service/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
