apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-portal-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: components/customer-portal/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
