apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-validator-cluster-us-west-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: components-tmc/data-validator/cluster-us-west-2
  destination:
    server: https://kubernetes.default.svc
    namespace: tmc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
