apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drift-detector-cluster-eu-west-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: components-tmc/drift-detector/cluster-eu-west-1
  destination:
    server: https://kubernetes.default.svc
    namespace: tmc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
