apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
    environment: dev
    version: 2.1.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: 2.1.5
    spec:
      containers:
      - name: auth-service
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: VERSION
          value: "2.1.5"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
