apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor-service
  namespace: data-platform
  labels:
    app: data-processor-service
    component-group: data-platform
    environment: prod
    version: 2.6.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processor-service
  template:
    metadata:
      labels:
        app: data-processor-service
        version: 2.6.0
    spec:
      containers:
      - name: data-processor-service
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: VERSION
          value: "2.5.0"
        - name: SERVICE_NAME
          value: "data-processor-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor-service
  namespace: data-platform
spec:
  selector:
    app: data-processor-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
