apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-service
  labels:
    app: analytics-service
    environment: prod
    version: 4.3.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        version: 4.3.0
    spec:
      containers:
      - name: analytics-service
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: VERSION
          value: "4.3.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics-service
