apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-router-service
  namespace: api-gateway
  labels:
    app: gateway-router-service
    component-group: api-gateway
    environment: dev
    version: 1.9.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-router-service
  template:
    metadata:
      labels:
        app: gateway-router-service
        version: 1.9.0
    spec:
      containers:
      - name: gateway-router-service
        image: httpd:2.4.62-alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: VERSION
          value: "1.9.0"
        - name: SERVICE_NAME
          value: "gateway-router-service"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-router-service
  namespace: api-gateway
spec:
  selector:
    app: gateway-router-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
