apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:grhili/cd-operator-test-manifests.git
    targetRevision: main
    path: components
    directory:
      recurse: true
      include: '*/prod/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
