apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grhili/cd-operator-test-manifests.git
    targetRevision: HEAD
    path: dev/metrics-collector
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
