apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
    environment: staging
    version: 2.2.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: 2.2.0
    spec:
      containers:
      - name: auth-service
        image: redis:7.4-alpine
        ports:
        - containerPort: 6379
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: VERSION
          value: "2.2.0"
        resources:
          requests:
            memory: "48Mi"
            cpu: "75m"
          limits:
            memory: "96Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
