apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app: payment-service
    environment: staging
    version: 3.2.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: 3.2.1
    spec:
      containers:
      - name: payment-service
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: VERSION
          value: "3.2.1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: payment-service
