---
apiVersion: v1
kind: Namespace
metadata:
  name: tmc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-engine
  namespace: tmc
  labels:
    app: recommendation-engine
    cluster: cluster-us-west-2
    tmc: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-engine
  template:
    metadata:
      labels:
        app: recommendation-engine
        version: "1.0.0"
        cluster: cluster-us-west-2
        tmc: "true"
    spec:
      containers:
      - name: recommendation-engine
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-engine
  namespace: tmc
  labels:
    app: recommendation-engine
    cluster: cluster-us-west-2
    tmc: "true"
spec:
  selector:
    app: recommendation-engine
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
